#!/usr/bin/env node
/**
 * CAF scripted helper (mechanical only)
 *
 * Purpose:
 * - Generate a MermaidJS diagram from the graph surface JSONL.
 * - Debug relationship integrity without loading large artifacts into prompts.
 *
 * Input:
 * - architecture_library/patterns/retrieval_surface_v1/pattern_graph_surface_v1.jsonl
 *
 * Output (CAF-managed; overwrite=true):
 * - architecture_library/patterns/caf_meta_v1/pattern_graph_v1.mmd
 *
 * Usage:
 *   node tools/caf-meta/generate_pattern_graph_mermaid_v1.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import { resolveRepoRoot } from '../caf/lib_repo_root_v1.mjs';

function die(msg, code = 1) {
  process.stderr.write(`${msg}\n`);
  process.exit(code);
}

function readJsonl(fileAbs) {
  const raw = fs.readFileSync(fileAbs, 'utf8');
  const lines = raw.split(/\r?\n/).map((l) => l.trim()).filter(Boolean);
  const out = [];
  for (let i = 0; i < lines.length; i++) {
    try {
      out.push(JSON.parse(lines[i]));
    } catch (e) {
      throw new Error(`Invalid JSONL at ${fileAbs}:${i + 1}: ${String(e?.message ?? e)}`);
    }
  }
  return out;
}

function escNodeId(id) {
  return `P_${String(id).replace(/[^a-zA-Z0-9_]/g, '_')}`;
}

function main() {
  const repoRoot = resolveRepoRoot();
  const inPath = path.join(repoRoot, 'architecture_library', 'patterns', 'retrieval_surface_v1', 'pattern_graph_surface_v1.jsonl');
  const outPath = path.join(repoRoot, 'architecture_library', 'patterns', 'caf_meta_v1', 'pattern_graph_v1.mmd');

  if (!fs.existsSync(inPath)) {
    die(`Missing graph surface: ${inPath}\nRun: node tools/caf-meta/build_split_retrieval_surfaces_v1.mjs`, 2);
  }

  const recs = readJsonl(inPath);

  const nodes = new Set();
  const edges = [];
  for (const r of recs) {
    const from = r?.id;
    if (!from) continue;
    nodes.add(String(from));
    const rels = Array.isArray(r.relations) ? r.relations : [];
    for (const rel of rels) {
      const kind = rel?.kind;
      const to = rel?.id;
      if (!kind || !to) continue;
      nodes.add(String(to));
      edges.push({ from: String(from), kind: String(kind), to: String(to) });
    }
  }

  const lines = [];
  lines.push('%% Auto-generated by tools/caf-meta/generate_pattern_graph_mermaid_v1.mjs');
  lines.push('graph TD');

  for (const id of [...nodes].sort()) {
    lines.push(`  ${escNodeId(id)}["${id}"]`);
  }

  const edgeLines = edges
    .sort((a, b) => {
      const ak = `${a.from}::${a.kind}::${a.to}`;
      const bk = `${b.from}::${b.kind}::${b.to}`;
      return ak < bk ? -1 : ak > bk ? 1 : 0;
    })
    .map((e) => `  ${escNodeId(e.from)} -->|${e.kind}| ${escNodeId(e.to)}`);

  lines.push(...edgeLines);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, lines.join('\n') + '\n', 'utf8');

  process.stdout.write(`${path.relative(repoRoot, outPath).replace(/\\/g, '/')}\n`);
}

main();
