#!/usr/bin/env node
/**
 * CAF scripted helper (mechanical only)
 *
 * Purpose:
 * - Provide tiny deterministic parsing helpers for feedback packets.
 * - Standardize packet header conventions for CAF-emitted packets.
 * - Enable gates to treat `Severity: advisory` as non-blocking.
 * - Enable resolved packet status to suppress blocking without deleting history.
 *
 * Packet conventions (v1):
 * - `- Date: YYYY-MM-DD`
 * - `- Generated By: CAF vX.Y.Z` (must appear immediately under Date)
 * - `- Status: pending|stale|resolved`
 * - `- Severity: blocker|advisory` (missing -> treated as blocker)
 *
 * Status rules:
 * - pending: created during the most recent command execution that emitted it.
 * - stale: carried over from an earlier run (unresolved).
 * - resolved: fixed; must NOT block gates.
 */

import fs from 'node:fs';
import path from 'node:path';

import { cafBulletStampLine } from './lib_caf_version_v1.mjs';

function normalize(s) {
  return String(s ?? '').trim();
}

function normalizeLower(s) {
  return normalize(s).toLowerCase();
}

export function parseFeedbackPacketSeverityFromText(packetText) {
  const txt = String(packetText ?? '');
  const m = txt.match(/^\s*-\s*Severity\s*:\s*([^\r\n#]+)\s*$/im);
  if (!m) return null;
  const v = normalizeLower(m[1]);
  if (!v) return null;
  if (v.includes('advisory')) return 'advisory';
  if (v.includes('blocker')) return 'blocker';
  // Unknown values are treated as blocking by callers.
  return v;
}

export function parseFeedbackPacketStatusFromText(packetText) {
  const txt = String(packetText ?? '');
  const m = txt.match(/^\s*-\s*Status\s*:\s*([^\r\n#]+)\s*$/im);
  if (!m) return null;
  const v = normalizeLower(m[1]);
  if (!v) return null;
  if (v.includes('resolved')) return 'resolved';
  if (v.includes('stale')) return 'stale';
  if (v.includes('pending')) return 'pending';
  // Unknown values are treated as pending by updaters.
  return v;
}

export function readFeedbackPacketSeveritySync(packetFileAbs) {
  try {
    const txt = fs.readFileSync(packetFileAbs, { encoding: 'utf8' });
    return parseFeedbackPacketSeverityFromText(txt);
  } catch {
    return null;
  }
}

export function readFeedbackPacketStatusSync(packetFileAbs) {
  try {
    const txt = fs.readFileSync(packetFileAbs, { encoding: 'utf8' });
    return parseFeedbackPacketStatusFromText(txt);
  } catch {
    return null;
  }
}

export function listFeedbackPacketFilesSync(packetsDirAbs) {
  try {
    return fs
      .readdirSync(packetsDirAbs, { withFileTypes: true })
      .filter((d) => d.isFile())
      .map((d) => d.name)
      .sort();
  } catch {
    return [];
  }
}

export function listBlockingFeedbackPacketFilesSync(packetsDirAbs) {
  const files = listFeedbackPacketFilesSync(packetsDirAbs);
  const out = [];
  for (const f of files) {
    const abs = path.join(packetsDirAbs, f);
    const status = readFeedbackPacketStatusSync(abs);
    if (status && String(status).toLowerCase().includes('resolved')) continue;

    const sev = readFeedbackPacketSeveritySync(abs);
    if (sev && String(sev).toLowerCase().includes('advisory')) continue;
    out.push(f);
  }
  return out;
}

export function dirHasBlockingFeedbackPacketsSync(packetsDirAbs) {
  return listBlockingFeedbackPacketFilesSync(packetsDirAbs).length > 0;
}

function pad2(n) {
  return String(n).padStart(2, '0');
}

export function nowDateYYYYMMDD() {
  const d = new Date();
  return `${d.getUTCFullYear()}-${pad2(d.getUTCMonth() + 1)}-${pad2(d.getUTCDate())}`;
}

export function nowStampYYYYMMDD() {
  const d = new Date();
  return `${d.getUTCFullYear()}${pad2(d.getUTCMonth() + 1)}${pad2(d.getUTCDate())}`;
}

function upsertHeaderLine(lines, key, value, insertAfterKeys = []) {
  const re = new RegExp(`^\\s*-\\s*${key}\\s*:\\s*`, 'i');
  const idx = lines.findIndex((l) => re.test(String(l ?? '')));
  const newLine = `- ${key}: ${value}`;
  if (idx >= 0) {
    lines[idx] = newLine;
    return;
  }

  // Insert after the last matching insertAfterKeys; else after first non-empty line; else at end.
  let insertAt = -1;
  for (const k of insertAfterKeys) {
    const kre = new RegExp(`^\\s*-\\s*${k}\\s*:\\s*`, 'i');
    const kidx = lines.findIndex((l) => kre.test(String(l ?? '')));
    if (kidx >= 0) insertAt = Math.max(insertAt, kidx);
  }
  if (insertAt >= 0) {
    lines.splice(insertAt + 1, 0, newLine);
    return;
  }

  const firstNonEmpty = lines.findIndex((l) => String(l ?? '').trim() !== '');
  if (firstNonEmpty >= 0) {
    lines.splice(firstNonEmpty + 1, 0, newLine);
    return;
  }

  lines.push(newLine);
}

export function setFeedbackPacketStatusInText(packetText, newStatus) {
  const txt = String(packetText ?? '');
  const lines = txt.split(/\r?\n/);
  upsertHeaderLine(lines, 'Status', String(newStatus ?? '').trim() || 'stale', ['Generated By', 'Date']);
  return lines.join('\n');
}

/**
 * Best-effort normalize a feedback packet header to CAF Packet conventions (v1).
 *
 * Goals:
 * - Ensure `- Date:` exists.
 * - Ensure `- Generated By: CAF vX.Y.Z` appears immediately under Date.
 * - Ensure `- Status: pending|stale|resolved` exists (default: pending).
 * - Ensure `- Severity:` exists (default: blocker) so gates can classify.
 *
 * This is used by older scripts that still assemble packet bodies manually.
 * It avoids large refactors while converging packet headers across tools.
 */
export function ensureFeedbackPacketHeaderV1(packetText, opts = {}) {
  const txt = String(packetText ?? '');
  const statusDefault = normalizeLower(opts?.status || 'pending');
  const severityDefault = normalizeLower(opts?.severity || 'blocker');
  const lines = txt.split(/\r?\n/);

  const dateRe = /^\s*-\s*Date\s*:\s*/i;
  const genRe = /^\s*-\s*Generated\s+By\s*:\s*/i;
  const statusRe = /^\s*-\s*Status\s*:\s*/i;
  const sevRe = /^\s*-\s*Severity\s*:\s*/i;

  // Ensure Date exists near the header. If absent, insert after title line (or at top).
  let dateIdx = lines.findIndex((l) => dateRe.test(String(l ?? '')));
  if (dateIdx < 0) {
    const titleIdx = lines.findIndex((l) => /^#\s+/.test(String(l ?? '')));
    const insertAt = titleIdx >= 0 ? titleIdx + 2 : 0;
    lines.splice(insertAt, 0, `- Date: ${nowDateYYYYMMDD()}`);
    dateIdx = lines.findIndex((l) => dateRe.test(String(l ?? '')));
  }

  // Ensure Generated By exists and is immediately after Date.
  const genLine = cafBulletStampLine();
  let genIdx = lines.findIndex((l) => genRe.test(String(l ?? '')));
  if (genIdx >= 0) {
    const existing = lines[genIdx];
    lines.splice(genIdx, 1);
    if (genIdx < dateIdx) dateIdx -= 1;
    lines.splice(dateIdx + 1, 0, existing.trim() || genLine);
  } else {
    lines.splice(dateIdx + 1, 0, genLine);
  }

  // Ensure Status exists and is immediately after Generated By.
  const genIdx2 = lines.findIndex((l) => genRe.test(String(l ?? '')));
  let statusIdx = lines.findIndex((l) => statusRe.test(String(l ?? '')));
  const statusLine = `- Status: ${statusDefault || 'pending'}`;
  if (statusIdx >= 0) {
    const existing = lines[statusIdx];
    lines.splice(statusIdx, 1);
    // Re-find gen index after splice.
    const genIdx3 = lines.findIndex((l) => genRe.test(String(l ?? '')));
    lines.splice(genIdx3 + 1, 0, existing.trim() || statusLine);
  } else {
    lines.splice(genIdx2 + 1, 0, statusLine);
  }

  // Ensure Severity exists (do not reorder if already present).
  const sevIdx = lines.findIndex((l) => sevRe.test(String(l ?? '')));
  if (sevIdx < 0) {
    const stuckIdx = lines.findIndex((l) => /^\s*-\s*Stuck\s+At\s*:\s*/i.test(String(l ?? '')));
    const instIdx = lines.findIndex((l) => /^\s*-\s*Instance\s*:\s*/i.test(String(l ?? '')));
    const statusIdx2 = lines.findIndex((l) => statusRe.test(String(l ?? '')));
    const ins = stuckIdx >= 0 ? stuckIdx + 1 : (instIdx >= 0 ? instIdx + 1 : (statusIdx2 >= 0 ? statusIdx2 + 1 : (genIdx2 + 2)));
    lines.splice(ins, 0, `- Severity: ${severityDefault || 'blocker'}`);
  }

  return lines.join('\n');
}

/**
 * Mark all pending packets as stale.
 * Also upserts Status=stale for legacy packets missing Status.
 * Never modifies resolved packets.
 */
export function markPendingFeedbackPacketsStaleSync(packetsDirAbs) {
  const files = listFeedbackPacketFilesSync(packetsDirAbs).filter((f) => f.toLowerCase().endsWith('.md'));
  for (const f of files) {
    const abs = path.join(packetsDirAbs, f);
    let txt;
    try {
      txt = fs.readFileSync(abs, { encoding: 'utf8' });
    } catch {
      continue;
    }
    const st = parseFeedbackPacketStatusFromText(txt);
    if (st && st.toLowerCase().includes('resolved')) continue;

    if (!st || st.toLowerCase().includes('pending')) {
      const next = setFeedbackPacketStatusInText(txt, 'stale');
      if (next !== txt) {
        try {
          fs.writeFileSync(abs, next, 'utf8');
        } catch {
          // best-effort
        }
      }
    }
  }
}

export function renderFeedbackPacketV1(params = {}) {
  const title = normalize(params.title) || 'CAF feedback packet';
  const instanceName = normalize(params.instanceName);
  const stuckAt = normalize(params.stuckAt);
  const severity = normalize(params.severity) || 'blocker';
  const status = normalize(params.status) || 'pending';
  const observedConstraint = normalize(params.observedConstraint);
  const gapType = normalize(params.gapType);
  const minimalFixLines = Array.isArray(params.minimalFixLines) ? params.minimalFixLines.map(normalize).filter(Boolean) : [];
  const evidenceLines = Array.isArray(params.evidenceLines) ? params.evidenceLines.map(normalize).filter(Boolean) : [];

  const headerDate = normalize(params.dateYYYYMMDD) || nowDateYYYYMMDD();

  const lines = [];
  lines.push(`# Feedback Packet - ${title}`);
  lines.push('');
  lines.push(`- Date: ${headerDate}`);
  lines.push(cafBulletStampLine());
  lines.push(`- Status: ${status}`);
  if (instanceName) lines.push(`- Instance: ${instanceName}`);
  if (stuckAt) lines.push(`- Stuck At: ${stuckAt}`);
  lines.push(`- Severity: ${severity}`);
  if (observedConstraint) lines.push(`- Observed Constraint: ${observedConstraint}`);
  if (gapType) lines.push(`- Gap Type: ${gapType}`);
  lines.push('');

  if (minimalFixLines.length > 0) {
    lines.push('## Minimal Fix Proposal');
    for (const l of minimalFixLines) lines.push(`- ${l}`);
    lines.push('');
  }

  if (evidenceLines.length > 0) {
    lines.push('## Evidence');
    for (const l of evidenceLines) lines.push(`- ${l}`);
    lines.push('');
  }

  // Stable, short guidance block.
  lines.push('## Autonomous agent guidance');
  lines.push('- Apply the Minimal Fix Proposal (do not invent alternatives).');
  lines.push('- Mark this packet as resolved by changing `- Status: ...` to `- Status: resolved`.');
  lines.push('- Then rerun the CAF command that produced this packet.');
  lines.push('');

  return lines.join('\n');
}
