/**
 * CAF version helper (mechanical only)
 *
 * Source of truth:
 * - <repoRoot>/VERSION (preferred) or <repoRoot>/CAF_VERSION (fallback)
 *
 * Notes:
 * - Version stamping is best-effort. Do NOT fail-closed on missing version.
 * - If VERSION/CAF_VERSION is missing/unreadable, return "0.0.0".
 */

import fs from 'node:fs';
import path from 'node:path';
import { resolveRepoRoot } from './lib_repo_root_v1.mjs';

export function readCafVersionSync(repoRootAbs) {
  try {
    const repoRoot = repoRootAbs ? path.resolve(repoRootAbs) : resolveRepoRoot();
    const preferred = path.join(repoRoot, 'VERSION');
    const fallback = path.join(repoRoot, 'CAF_VERSION');
    const p = fs.existsSync(preferred) ? preferred : fallback;
    const raw = fs.readFileSync(p, { encoding: 'utf8' });
    const v = String(raw ?? '').trim();
    return v || '0.0.0';
  } catch {
    return '0.0.0';
  }
}

/**
 * Safe for Markdown / HTML-commentable text formats.
 * Intentionally includes only the CAF version (no tool paths) to keep user-facing
 * artifacts clean and stable.
 */
export function cafMarkdownStampLine() {
  const v = readCafVersionSync();
  return `<!-- Generated by CAF v${v} -->`;
}

/**
 * Safe for YAML (comment line).
 * Intentionally includes only the CAF version (no tool paths).
 */
export function cafYamlStampLine() {
  const v = readCafVersionSync();
  return `# Generated by CAF v${v}`;
}

/**
 * Safe for CAF feedback packet Markdown (bullet list in header).
 * Intentionally includes only the CAF version (no tool paths).
 */
export function cafBulletStampLine() {
  const v = readCafVersionSync();
  return `- Generated By: CAF v${v}`;
}
