#!/usr/bin/env node
/**
 * CAF scripted helper (mechanical only)
 *
 * Purpose:
 * - Deterministically ensure Python package marker files ("__init__.py") exist
 *   for candidate code packages under the instance companion repo.
 * - This supports dotted-module entrypoints (e.g., "code.ap.main:app") and
 *   prevents broken imports caused by missing package markers.
 *
 * Constraints:
 * - No architecture decisions.
 * - No stack selection.
 * - Deterministic filesystem operations only.
 * - Fail-closed on guardrails violations (writes outside allowed paths).
 */

import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import { resolveRepoRoot } from './lib_repo_root_v1.mjs';
import { getInstanceLayout } from './lib_instance_layout_v1.mjs';
import { parseYamlString } from './lib_yaml_v2.mjs';
import { readCafVersionSync } from './lib_caf_version_v1.mjs';

const NAME_RE = /^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$/;

class CafExit extends Error {
  constructor(code, msg) {
    super(msg);
    this.code = code;
  }
}

function die(msg, code = 1) {
  throw new CafExit(code, msg);
}

function normalizePrefix(p) {
  const s = String(p || '').replace(/\\/g, '/');
  return s.endsWith('/') ? s : `${s}/`;
}

function isWithinAllowedWritePaths(targetRel, allowedWritePaths) {
  const t = normalizePrefix(targetRel);
  for (const awp of allowedWritePaths) {
    const prefix = normalizePrefix(String(awp));
    if (t.startsWith(prefix)) return true;
  }
  return false;
}

async function readUtf8(p) {
  return await fs.readFile(p, { encoding: 'utf8' });
}

async function ensureDir(dirAbs) {
  await fs.mkdir(dirAbs, { recursive: true });
}

async function listDirsRecursive(rootAbs) {
  const out = [];
  const stack = [rootAbs];
  while (stack.length > 0) {
    const cur = stack.pop();
    out.push(cur);
    let entries;
    try {
      entries = await fs.readdir(cur, { withFileTypes: true });
    } catch {
      continue;
    }
    for (const ent of entries) {
      if (ent.isDirectory()) {
        stack.push(path.join(cur, ent.name));
      }
    }
  }
  return out;
}

async function findPythonFileDirs(codeRootAbs) {
  const dirs = new Set();
  const stack = [codeRootAbs];
  while (stack.length > 0) {
    const cur = stack.pop();
    let entries;
    try {
      entries = await fs.readdir(cur, { withFileTypes: true });
    } catch {
      continue;
    }
    let hasPy = false;
    for (const ent of entries) {
      if (ent.isFile() && ent.name.toLowerCase().endsWith('.py')) {
        hasPy = true;
      }
    }
    if (hasPy) dirs.add(cur);
    for (const ent of entries) {
      if (ent.isDirectory()) stack.push(path.join(cur, ent.name));
    }
  }
  return Array.from(dirs);
}

function parentDirsUpTo(childAbs, rootAbs) {
  const out = [];
  let cur = path.resolve(childAbs);
  const root = path.resolve(rootAbs);
  while (true) {
    out.push(cur);
    if (cur === root) break;
    const next = path.dirname(cur);
    if (next === cur) break;
    cur = next;
    if (!cur.startsWith(root)) break;
  }
  return out;
}

function renderInitFile(instanceName) {
  const v = readCafVersionSync();
  return [
    `# Generated by CAF v${v}`,
    `# CAF_TRACE: capability=python_package_markers_materialization instance=${instanceName} tool=materialize_python_package_inits_v1`,
    '',
  ].join('\n');
}

async function loadGuardrailsResolved(repoRoot, layout) {
  const railsPath = path.join(layout.specGuardrailsDir, 'profile_parameters_resolved.yaml');
  if (!existsSync(railsPath)) {
    die(`Missing guardrails: ${path.relative(repoRoot, railsPath).replace(/\\/g, '/')}`, 10);
  }
  const railsObj = parseYamlString(await readUtf8(railsPath), railsPath);
  const allowed = Array.isArray(railsObj?.lifecycle?.allowed_write_paths) ? railsObj.lifecycle.allowed_write_paths : [];
  if (allowed.length === 0) {
    die('Guardrails invalid: lifecycle.allowed_write_paths missing/empty', 11);
  }
  const companionRepoTarget = String(railsObj?.companion_repo_target || '').trim();
  if (!companionRepoTarget) {
    die('Guardrails invalid: companion_repo_target missing/empty', 12);
  }
  if (!isWithinAllowedWritePaths(companionRepoTarget, allowed)) {
    die('Guardrails invalid: companion_repo_target is not within lifecycle.allowed_write_paths', 13);
  }
  return { railsObj, allowedWritePaths: allowed, companionRepoTarget };
}

async function loadPythonTbpCodeRoot(repoRoot) {
  const tbpManifestPath = path.join(repoRoot, 'architecture_library', 'phase_8', 'tbp', 'atoms', 'TBP-PY-01', 'tbp_manifest_v1.yaml');
  if (!existsSync(tbpManifestPath)) return 'code/';
  try {
    const obj = parseYamlString(await readUtf8(tbpManifestPath), tbpManifestPath);
    const codeRoot = String(obj?.layout?.code_root || 'code/').trim();
    if (!codeRoot) return 'code/';
    return codeRoot.endsWith('/') ? codeRoot : `${codeRoot}/`;
  } catch {
    return 'code/';
  }
}

export async function internal_main(argv = process.argv.slice(2)) {
  const args = Array.isArray(argv) ? argv : [];
  if (args.length < 1) die('Usage: node tools/caf/materialize_python_package_inits_v1.mjs <instance_name>', 2);
  const instanceName = args[0];
  if (!NAME_RE.test(instanceName)) die(`Invalid instance_name: ${instanceName}`, 2);

  const repoRoot = resolveRepoRoot();
  const layout = getInstanceLayout(repoRoot, instanceName);

  const { allowedWritePaths, companionRepoTarget } = await loadGuardrailsResolved(repoRoot, layout);
  const companionRootAbs = path.join(repoRoot, companionRepoTarget);

  // Ensure companion repo exists (do not create the whole repo; that is companion_init's job).
  if (!existsSync(companionRootAbs)) {
    die(`Missing companion repo target: ${path.relative(repoRoot, companionRootAbs).replace(/\\/g, '/')}`, 20);
  }

  const codeRootRel = await loadPythonTbpCodeRoot(repoRoot);
  const codeRootAbs = path.join(companionRootAbs, codeRootRel);

  // Always ensure the code root directory exists for the marker file.
  await ensureDir(codeRootAbs);

  const initText = renderInitFile(instanceName);

  // Determine package directories:
  // - Always include the code root itself.
  // - Include every directory containing *.py, plus all parents up to code root.
  const pyDirs = await findPythonFileDirs(codeRootAbs);
  const pkgDirs = new Set([path.resolve(codeRootAbs)]);
  for (const d of pyDirs) {
    for (const p of parentDirsUpTo(d, codeRootAbs)) {
      pkgDirs.add(path.resolve(p));
    }
  }

  // Also include any immediate plane roots if they exist (common CAF layout): code/ap, code/cp.
  for (const plane of ['ap', 'cp']) {
    const p = path.join(codeRootAbs, plane);
    if (existsSync(p)) pkgDirs.add(path.resolve(p));
  }

  const created = [];
  const blocked = [];

  for (const dirAbs of Array.from(pkgDirs).sort()) {
    const initAbs = path.join(dirAbs, '__init__.py');
    if (existsSync(initAbs)) continue;

    const initRel = path.relative(repoRoot, initAbs).replace(/\\/g, '/');
    // Guardrails check against allowed_write_paths (relative paths).
    const ok = allowedWritePaths.some((p) => normalizePrefix(initRel).startsWith(normalizePrefix(p)));
    if (!ok) {
      blocked.push(initRel);
      continue;
    }

    await ensureDir(path.dirname(initAbs));
    await fs.writeFile(initAbs, initText, { encoding: 'utf8' });
    created.push(initRel);
  }

  if (blocked.length > 0) {
    die(`Write blocked by guardrails for one or more package marker paths: ${blocked.join(', ')}`, 30);
  }

  // No-op is allowed (already correct).
  const summary = {
    instance: instanceName,
    code_root: path.relative(repoRoot, codeRootAbs).replace(/\\/g, '/'),
    created_count: created.length,
  };

  // Print a single-line summary for operator logs.
  console.log(JSON.stringify(summary));
}

export async function main() {
  try {
    await internal_main(process.argv.slice(2));
  } catch (e) {
    if (e instanceof CafExit) {
      console.error(String(e.message || e));
      process.exit(e.code);
    }
    console.error(String(e?.stack || e));
    process.exit(1);
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}
