#!/usr/bin/env node
/**
 * CAF scripted helper (mechanical only)
 *
 * Purpose:
 * - Deterministically seed a new reference architecture instance by copying the two Phase 8
 *   profile template YAML files into the instance playbook/guardrails with the same substitutions
 *   as caf-saas-init.
 *
 * Constraints:
 * - No architecture decisions.
 * - No pattern selection.
 * - Deterministic, bounded substitutions only.
 * - Fail-closed: on post-validation failure, write a feedback packet under the instance.
 */

import fs from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { resolveRepoRoot } from './lib_repo_root_v1.mjs';
import { parseYamlString } from './lib_yaml_v2.mjs';
import { annotateSeededTemplateDefault, dumpYamlStable } from './lib_shape_lifecycle_v1.mjs';
import { markPendingFeedbackPacketsStaleSync, renderFeedbackPacketV1, nowStampYYYYMMDD } from './lib_feedback_packets_v1.mjs';
import { readCafVersionSync } from './lib_caf_version_v1.mjs';

const NAME_RE = /^[a-z][a-z0-9]*(?:[-_][a-z0-9]+)*$/;

class CafExit extends Error {
  constructor(code, msg) {
    super(msg);
    this.code = code;
  }
}

function die(msg, code = 1) {
  throw new CafExit(code, msg);
}

function nowStamp() {
  // YYYYMMDDTHHMMSSZ (safe for filenames)
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  const yyyy = d.getUTCFullYear();
  const mm = pad(d.getUTCMonth() + 1);
  const dd = pad(d.getUTCDate());
  const hh = pad(d.getUTCHours());
  const mi = pad(d.getUTCMinutes());
  const ss = pad(d.getUTCSeconds());
  return `${yyyy}${mm}${dd}T${hh}${mi}${ss}Z`;
}

function findPlaceholders(text) {
  // Any <...> token remaining is treated as a placeholder.
  // Keep it simple and explicit; this mirrors the skill contract.
  const re = /<[^>\n]{1,80}>/g;
  return Array.from(String(text ?? '').matchAll(re)).map((m) => m[0]);
}

function hasPrdPlaceholders(text) {
  // Keep in lockstep with tools/caf/prd_extract_v1.mjs placeholder hygiene.
  // NOTE: this is intentionally strict ("<" is disallowed anywhere) to avoid
  // later fail-closed extraction.
  const t = String(text ?? '').toLowerCase();
  return t.includes('<') || t.includes('tbd') || t.includes('todo') || t.includes('unknown');
}

function ensureYamlStampTop(content, stampLine) {
  const lines = String(content ?? '').split(/\r?\n/);
  const firstIdx = lines.findIndex((l) => String(l).trim() !== '');
  if (firstIdx === -1) {
    return `${stampLine}\n`;
  }
  if (String(lines[firstIdx]).trim() === stampLine) {
    return String(content ?? '');
  }
  lines.splice(firstIdx, 0, stampLine);
  return lines.join('\n');
}

function ensureMarkdownStampTop(content, stampLine) {
  const lines = String(content ?? '').split(/\r?\n/);
  const firstIdx = lines.findIndex((l) => String(l).trim() !== '');
  if (firstIdx === -1) {
    return `${stampLine}\n`;
  }
  const first = String(lines[firstIdx]).trim();
  if (first === stampLine || first.startsWith('<!-- Generated by CAF v')) {
    return String(content ?? '');
  }
  lines.splice(firstIdx, 0, stampLine);
  return lines.join('\n');
}

async function readUtf8(p) {
  return await fs.readFile(p, { encoding: 'utf8' });
}

async function writeUtf8(p, content) {
  await fs.writeFile(p, content, { encoding: 'utf8' });
}

async function ensureDir(p) {
  await fs.mkdir(p, { recursive: true });
}

export async function internal_main(argv = process.argv.slice(2)) {
  const args = Array.isArray(argv) ? argv : [];
  if (args.length < 2) {
    die('Usage: node tools/caf/seed_saas_v1.mjs <instance_name> <profile_template_id> [--overwrite]', 2);
  }

  const instanceName = args[0];
  const profileTemplateId = args[1];
  const overwrite = args.includes('--overwrite');

  if (!NAME_RE.test(instanceName)) {
    die(`Invalid instance_name: ${instanceName}`, 2);
  }
  if (!NAME_RE.test(profileTemplateId)) {
    die(`Invalid profile_template_id: ${profileTemplateId}`, 2);
  }

  // Repo root is the current working directory.
  const repoRoot = resolveRepoRoot();
  const cafVersion = readCafVersionSync(repoRoot);

  // Ensure the instance root container exists (fresh checkouts may not have it).
  // This must be deterministic and mechanical.
  await ensureDir(path.join(repoRoot, 'reference_architectures'));

  const srcPlaybook = path.join(
    repoRoot,
    'architecture_library',
    'phase_8',
    'profile_templates',
    profileTemplateId,
    'architecture_shape_parameters_template_v1.yaml'
  );
  const srcGuardrails = path.join(
    repoRoot,
    'architecture_library',
    'phase_8',
    'profile_templates',
    profileTemplateId,
    'profile_parameters_template_v1.yaml'
  );

  const srcPrdSample = path.join(
    repoRoot,
    'architecture_library',
    'phase_8',
    'profile_templates',
    profileTemplateId,
    'prd_v1.sample.md'
  );
  const shouldCopyPrdSample = existsSync(srcPrdSample);

  const srcPlatformPrdSample = path.join(
    repoRoot,
    'architecture_library',
    'phase_8',
    'profile_templates',
    profileTemplateId,
    'platform_prd_v1.sample.md'
  );
  const shouldCopyPlatformPrdSample = existsSync(srcPlatformPrdSample);

  const srcUxVisionSample = path.join(
    repoRoot,
    'architecture_library',
    'phase_8',
    'profile_templates',
    profileTemplateId,
    'ux_vision_v1.sample.md'
  );
  const shouldCopyUxVisionSample = existsSync(srcUxVisionSample);

  // Preconditions: sources must exist.
  if (!existsSync(srcPlaybook)) {
    die(`Missing source: ${path.relative(repoRoot, srcPlaybook)}`, 3);
  }
  if (!existsSync(srcGuardrails)) {
    die(`Missing source: ${path.relative(repoRoot, srcGuardrails)}`, 3);
  }

  // New folder contract (no back-compat): spec/ vs design/ split.
  // Seed only the spec-stage YAMLs; create the design root dirs for rerun hygiene.
  const instRoot = path.join(repoRoot, 'reference_architectures', instanceName);
  const instSpecRoot = path.join(instRoot, 'spec');
  const instDesignRoot = path.join(instRoot, 'design');

  const instPlaybookDir = path.join(instSpecRoot, 'playbook');
  const instGuardrailsDir = path.join(instSpecRoot, 'guardrails');
  const instMetaDir = path.join(instSpecRoot, 'caf_meta');
  const instDesignPlaybookDir = path.join(instDesignRoot, 'playbook');
  const instPacketsDir = path.join(instRoot, 'feedback_packets');
  const instProductDir = path.join(instRoot, 'product');

  const dstPlaybook = path.join(instPlaybookDir, 'architecture_shape_parameters.yaml');
  const dstGuardrails = path.join(instGuardrailsDir, 'profile_parameters.yaml');
  const dstPrd = path.join(instProductDir, 'PRD.md');
  const dstPlatformPrd = path.join(instProductDir, 'PLATFORM_PRD.md');
  const dstUxVision = path.join(instProductDir, 'UX_VISION.md');

  // Preconditions: destination must not exist unless overwrite=true.
  if (!overwrite) {
    if (existsSync(dstPlaybook)) {
      die(`Destination exists (overwrite=false): ${path.relative(repoRoot, dstPlaybook)}`, 4);
    }
    if (existsSync(dstGuardrails)) {
      die(`Destination exists (overwrite=false): ${path.relative(repoRoot, dstGuardrails)}`, 4);
    }
    if (shouldCopyPrdSample && existsSync(dstPrd)) {
      die(`Destination exists (overwrite=false): ${path.relative(repoRoot, dstPrd)}`, 4);
    }
    if (shouldCopyPlatformPrdSample && existsSync(dstPlatformPrd)) {
      die(`Destination exists (overwrite=false): ${path.relative(repoRoot, dstPlatformPrd)}`, 4);
    }
    if (shouldCopyUxVisionSample && existsSync(dstUxVision)) {
      die(`Destination exists (overwrite=false): ${path.relative(repoRoot, dstUxVision)}`, 4);
    }
  }

  // Create dirs only after preconditions pass.
  await ensureDir(path.join(repoRoot, 'reference_architectures'));
  await ensureDir(instPlaybookDir);
  await ensureDir(instGuardrailsDir);
  await ensureDir(instMetaDir);
  await ensureDir(instDesignPlaybookDir);
  await ensureDir(instPacketsDir);

  // Command-start packet hygiene: mark prior pending packets as stale (best-effort).
  try { markPendingFeedbackPacketsStaleSync(instPacketsDir); } catch { /* best-effort */ }
  if (shouldCopyPrdSample || shouldCopyPlatformPrdSample || shouldCopyUxVisionSample) {
    await ensureDir(instProductDir);
  }

  // Read sources.
  let playbookContent = await readUtf8(srcPlaybook);
  let guardrailsContent = await readUtf8(srcGuardrails);
  let prdSampleContent = '';
  if (shouldCopyPrdSample) {
    prdSampleContent = await readUtf8(srcPrdSample);
  }

  let platformPrdSampleContent = '';
  if (shouldCopyPlatformPrdSample) {
    platformPrdSampleContent = await readUtf8(srcPlatformPrdSample);
  }

  let uxVisionSampleContent = '';
  if (shouldCopyUxVisionSample) {
    uxVisionSampleContent = await readUtf8(srcUxVisionSample);
  }

  // Minimal safe substitutions (instance-name only).
  // Playbook substitutions.
  playbookContent = playbookContent.split('{{instance_name}}').join(instanceName);
  playbookContent = playbookContent.split('"intentionally_boring_saas"').join(`"${instanceName}"`);

  // Guardrails substitutions.
  guardrailsContent = guardrailsContent.split('<REFERENCE_ARCHITECTURE_NAME>').join(instanceName);
  guardrailsContent = guardrailsContent.split('<name>').join(instanceName);
  guardrailsContent = guardrailsContent.split('{{instance_name}}').join(instanceName);

  // Guardrails metadata defaults.
  guardrailsContent = guardrailsContent.split('change_reason: ""').join('change_reason: "initial_instance_creation"');
  guardrailsContent = guardrailsContent.split("change_reason: ''").join("change_reason: 'initial_instance_creation'");
  guardrailsContent = guardrailsContent.split('notes: ""').join('notes: "Initialized by caf-saas-init."');
  guardrailsContent = guardrailsContent.split("notes: ''").join("notes: 'Initialized by caf-saas-init.'");

  // Backfill lifecycle provenance for legacy templates that do not carry it yet.
  if (!playbookContent.includes('lifecycle_shape_status:')) {
    const seededObj = annotateSeededTemplateDefault(parseYamlString(playbookContent));
    playbookContent = dumpYamlStable(seededObj);
  }

  // Placeholder scan (fail-closed).
  const remaining = [
    ...new Set([...findPlaceholders(playbookContent), ...findPlaceholders(guardrailsContent)]),
  ];
  if (remaining.length > 0) {
    const yyyyMMdd = nowStampYYYYMMDD();
    const packetPath = path.join(instPacketsDir, `BP-${yyyyMMdd}-caf-saas-init-placeholders-remain.md`);
    const relPacket = path.relative(repoRoot, packetPath);
    const relPlaybook = path.relative(repoRoot, dstPlaybook);
    const relGuardrails = path.relative(repoRoot, dstGuardrails);
    const relSrcPlaybook = path.relative(repoRoot, srcPlaybook);
    const relSrcGuardrails = path.relative(repoRoot, srcGuardrails);

    const body = renderFeedbackPacketV1({
      title: 'caf-saas-init',
      instanceName,
      stuckAt: 'tools/caf/seed_saas_v1.mjs',
      severity: 'blocker',
      status: 'pending',
      observedConstraint: 'placeholder tokens of the form <...> remain after allowed substitutions',
      gapType: 'Missing input',
      minimalFixLines: [
        'Inspect the profile template YAMLs and replace remaining placeholders with safe defaults or make them architect-editable in a later phase.',
        `Source playbook template: ${relSrcPlaybook}`,
        `Source guardrails template: ${relSrcGuardrails}`,
      ],
      evidenceLines: [
        `Attempted destinations:`,
        `  - ${relPlaybook}`,
        `  - ${relGuardrails}`,
        'Remaining placeholders:',
        ...remaining.map((x) => `  - ${x}`),
      ],
    });

    await writeUtf8(packetPath, body);
    die(`Fail-closed: placeholders remain. Wrote feedback packet: ${relPacket}`, 5);
  }

  if (shouldCopyPrdSample && hasPrdPlaceholders(prdSampleContent)) {
    const yyyyMMdd = nowStampYYYYMMDD();
    const packetPath = path.join(instPacketsDir, `BP-${yyyyMMdd}-caf-saas-init-prd-sample-not-extractable.md`);
    const relPacket = path.relative(repoRoot, packetPath);
    const relDst = path.relative(repoRoot, dstPrd);
    const relSrc = path.relative(repoRoot, srcPrdSample);

    const body = renderFeedbackPacketV1({
      title: 'caf-saas-init',
      instanceName,
      stuckAt: 'tools/caf/seed_saas_v1.mjs',
      severity: 'blocker',
      status: 'pending',
      observedConstraint: 'PRD sample contains placeholder-like tokens ("<", TBD, TODO, UNKNOWN)',
      gapType: 'Spec violation',
      minimalFixLines: [
        'Edit the PRD sample to remove placeholder-like tokens and commit a fully filled example.',
        `Source PRD sample: ${relSrc}`,
      ],
      evidenceLines: [
        `Intended destination: ${relDst}`,
      ],
    });

    await writeUtf8(packetPath, body);
    die(`Fail-closed: PRD sample is not extractable. Wrote feedback packet: ${relPacket}`, 5);
  }

  if (shouldCopyPlatformPrdSample && hasPrdPlaceholders(platformPrdSampleContent)) {
    const yyyyMMdd = nowStampYYYYMMDD();
    const packetPath = path.join(instPacketsDir, `BP-${yyyyMMdd}-caf-saas-init-platform-prd-sample-not-extractable.md`);
    const relPacket = path.relative(repoRoot, packetPath);
    const relDst = path.relative(repoRoot, dstPlatformPrd);
    const relSrc = path.relative(repoRoot, srcPlatformPrdSample);

    const body = renderFeedbackPacketV1({
      title: 'caf-saas-init',
      instanceName,
      stuckAt: 'tools/caf/seed_saas_v1.mjs',
      severity: 'blocker',
      status: 'pending',
      observedConstraint: 'Platform PRD sample contains placeholder-like tokens ("<", TBD, TODO, UNKNOWN)',
      gapType: 'Spec violation',
      minimalFixLines: [
        'Edit the Platform PRD sample to remove placeholder-like tokens and commit a fully filled example.',
        `Source Platform PRD sample: ${relSrc}`,
      ],
      evidenceLines: [
        `Intended destination: ${relDst}`,
      ],
    });

    await writeUtf8(packetPath, body);
    die(`Fail-closed: Platform PRD sample is not extractable. Wrote feedback packet: ${relPacket}`, 5);
  }

  if (shouldCopyUxVisionSample && hasPrdPlaceholders(uxVisionSampleContent)) {
    const yyyyMMdd = nowStampYYYYMMDD();
    const packetPath = path.join(instPacketsDir, `BP-${yyyyMMdd}-caf-saas-init-ux-vision-sample-not-extractable.md`);
    const relPacket = path.relative(repoRoot, packetPath);
    const relDst = path.relative(repoRoot, dstUxVision);
    const relSrc = path.relative(repoRoot, srcUxVisionSample);

    const body = renderFeedbackPacketV1({
      title: 'caf-saas-init',
      instanceName,
      stuckAt: 'tools/caf/seed_saas_v1.mjs',
      severity: 'blocker',
      status: 'pending',
      observedConstraint: 'UX_VISION sample contains placeholder-like tokens ("<", TBD, TODO, UNKNOWN)',
      gapType: 'Spec violation',
      minimalFixLines: [
        'Edit the UX_VISION sample to remove placeholder-like tokens and commit a fully filled example.',
        `Source UX_VISION sample: ${relSrc}`,
      ],
      evidenceLines: [
        `Intended destination: ${relDst}`,
      ],
    });

    await writeUtf8(packetPath, body);
    die(`Fail-closed: UX_VISION sample is not extractable. Wrote feedback packet: ${relPacket}`, 5);
  }

  // Best-effort provenance stamp (safe only for text formats).
  const yamlStamp = `# Generated by CAF v${cafVersion}`;
  const mdStamp = `<!-- Generated by CAF v${cafVersion} -->`;

  playbookContent = ensureYamlStampTop(playbookContent, yamlStamp);
  guardrailsContent = ensureYamlStampTop(guardrailsContent, yamlStamp);
  if (shouldCopyPrdSample) {
    prdSampleContent = ensureMarkdownStampTop(prdSampleContent, mdStamp);
  }
  if (shouldCopyPlatformPrdSample) {
    platformPrdSampleContent = ensureMarkdownStampTop(platformPrdSampleContent, mdStamp);
  }
  if (shouldCopyUxVisionSample) {
    uxVisionSampleContent = ensureMarkdownStampTop(uxVisionSampleContent, mdStamp);
  }

  // Write destinations.
  await writeUtf8(dstPlaybook, playbookContent);
  await writeUtf8(dstGuardrails, guardrailsContent);
  if (shouldCopyPrdSample) {
    await writeUtf8(dstPrd, prdSampleContent);
  }
  if (shouldCopyPlatformPrdSample) {
    await writeUtf8(dstPlatformPrd, platformPrdSampleContent);
  }
  if (shouldCopyUxVisionSample) {
    await writeUtf8(dstUxVision, uxVisionSampleContent);
  }

  // Verify.
  const rb = await readUtf8(dstPlaybook);
  const rg = await readUtf8(dstGuardrails);
  if (rb !== playbookContent) {
    die(`Verification failed for ${path.relative(repoRoot, dstPlaybook)}`, 6);
  }
  if (rg !== guardrailsContent) {
    die(`Verification failed for ${path.relative(repoRoot, dstGuardrails)}`, 6);
  }
  if (shouldCopyPrdSample) {
    const rp = await readUtf8(dstPrd);
    if (rp !== prdSampleContent) {
      die(`Verification failed for ${path.relative(repoRoot, dstPrd)}`, 6);
    }
  }
  if (shouldCopyPlatformPrdSample) {
    const rp = await readUtf8(dstPlatformPrd);
    if (rp !== platformPrdSampleContent) {
      die(`Verification failed for ${path.relative(repoRoot, dstPlatformPrd)}`, 6);
    }
  }
  if (shouldCopyUxVisionSample) {
    const rp = await readUtf8(dstUxVision);
    if (rp !== uxVisionSampleContent) {
      die(`Verification failed for ${path.relative(repoRoot, dstUxVision)}`, 6);
    }
  }

  // Success output (paths only).
  console.log(`Initialized reference_architectures/${instanceName}`);
  console.log(`reference_architectures/${instanceName}/spec/playbook/architecture_shape_parameters.yaml`);
  console.log(`reference_architectures/${instanceName}/spec/guardrails/profile_parameters.yaml`);
  if (shouldCopyPrdSample) {
    console.log(`reference_architectures/${instanceName}/product/PRD.md`);
  }
  if (shouldCopyPlatformPrdSample) {
    console.log(`reference_architectures/${instanceName}/product/PLATFORM_PRD.md`);
  }
  if (shouldCopyUxVisionSample) {
    console.log(`reference_architectures/${instanceName}/product/UX_VISION.md`);
  }
}

async function main() {
  try {
    await internal_main(process.argv.slice(2));
  } catch (err) {
    if (err instanceof CafExit) {
      process.stderr.write(`${err.message}\n`);
      process.exit(err.code);
    }
    throw err;
  }
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  await main();
}
